spring.application.name=lifelink-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres

spring.datasource.username=postgres.eupuxljictmoohucfopz

spring.datasource.password=vikasni@200527

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.maximum-pool-size=5

groq.api.key=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

# Enable Spring Security debug logging for request matching and authorization
logging.level.org.springframework.security=DEBUG
spring.security.debug=true